### ISSUE TITLE
Retrieve Multiple Private Keys

### ISSUE THREAD

**Issue by AyushBherwani1998** [fuseio/wallet_core#29]
Is there any way to retrieve multiple private keys from a single Wallet seed? Normally we can have retrieve multiple accounts from master private key derived from the wallet seed, correct me if I'm wrong.

**Comment by vassilyvv** [comment]
This feature is definetely must be implemented. It should be possible to create unlimited number of PK's. Every user in my database is having his own address (generated from one mnemonic) to send tokens to. I'd like to have an option to see all the transactions to each of addresses that I have access to.

**Comment by LiorAgnin** [comment]
=

**Comment by LiorAgnin** [comment]
@AyushBherwani1998 We have added this feature

**Comment by AyushBherwani1998** [comment]
Awesome, thanks @LiorAgnin . I'll check this out
