### ISSUE TITLE
Why is strength not exposed in generateMnemonic function?

### ISSUE THREAD

**Issue by wal33d006** [fuseio/wallet_core#66]
I can see `bip39.generateMnemonic` from `package:bip39/bip39.dart` gives the privilege of varying the strength. Why does `generateMnemonic` not do that? I want to generate a mnemonic with 256 strength.

**Comment by leonprou** [comment]
Hey @wal33d006,
Seems that we can expose that functionality. The core team is busy with current tasks. So if you can open a PR to fix, this will hurry the things up.
@LiorAgnin do you have any objections?

**Comment by wal33d006** [comment]
Awesome! Will open a PR in a couple of hours.

**Comment by wal33d006** [comment]
@leonprou 
PR #67

**Comment by leonprou** [comment]
Thanks @wal33d006,
me and @LiorAgnin will check this

**Comment by leonprou** [comment]
Hey @wal33d006.
We added this to one of our latest releases. https://github.com/fuseio/wallet_core/blob/master/lib/src/web3.dart#L49
